[workspace]
members = [
    "bindgen-citro3d",
    "citro3d-macros",
    "citro3d-sys",
    "citro3d",
]
default-members = [
    "citro3d",
    "citro3d-sys",
    "citro3d-macros",
]
resolver = "2"

[patch."https://github.com/rust3ds/citro3d-rs.git"]
citro3d-sys = { path = "citro3d-sys" }
