[package]
name = "citro3d-sys"
version = "0.1.0"
authors = [ "Rust3DS Org", "panicbit <panicbit.dev@gmail.com>" ]
edition = "2021"
license = "Zlib"

[dependencies]
libc = "0.2.116"
ctru-sys = { git = "https://github.com/rust3ds/ctru-rs.git" }
