name: docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    permissions:
      id-token: write
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - uses: rust3ds/test-runner/setup@v1
        with:
          toolchain: nightly

      - name: Build workspace docs
        run: cargo 3ds --verbose doc --verbose --no-deps --workspace

      - name: Upload generated docs
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./target/armv6k-nintendo-3ds/doc

      - name: Deploy GitHub pages
        uses: actions/deploy-pages@v2

