name: GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - uses: rust3ds/test-runner/setup@v1
        with:
          toolchain: nightly

      - name: Build workspace docs
        run: cargo 3ds --verbose doc --verbose --no-deps --workspace

      - name: Upload generated docs
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./target/armv6k-nintendo-3ds/doc
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

